- name: Configure web servers
  hosts: webservers
  become: true

  vars:
    project_name: "Terraform 3-Tier App"
    db_endpoint: "mydb-instance.c9akcihdf8.us-east-1.rds.amazonaws.com"

  tasks:
    - name: Ensure httpd is installed
      package:
        name: httpd
        state: present

    - name: Ensure httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: true

    - name: Deploy sample page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head><title>{{ project_name }}</title></head>
            <body>
              <h1>Welcome to {{ project_name }} (Auto-provisioned)</h1>
              <p>App server connected to DB endpoint: {{ db_endpoint }}</p>
            </body>
          </html>
